version: "3.9"

services:
  postgres:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fast-api:
    build: /back/
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000

volumes:
  postgres_data:
