version: "3.9"

services:
  postgres:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network
      - public_network

  fast-api:
    build: /back/
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres
    networks:
      - internal_network
      - public_network

  frontend:
    build: ./front
    volumes:
      - ./front:/app # Для разработки (можно удалить в продакшене)
      - /app/node_modules
    command: sh -c "npm run build && tail -f /dev/null" # Завершаем командой, которая не завершается
    restart: unless-stopped
    depends_on:
      - fast-api
    networks:
      - internal_network

  nginx:
    build: /nginx/
    ports:
      - "80:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html # Монтируем билд фронтенда
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - internal_network
      - public_network

volumes:
  postgres_data:

networks:
  internal_network:
    internal: True
  public_network:
